# Created by Max Howell

FIND_LIBRARY (SQLITE3_LIBRARIES NAMES sqlite3 sqlite3)
FIND_PATH (SQLITE3_INCLUDE_DIR sqlite3.h sqlite)

INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Sqlite3 DEFAULT_MSG SQLITE3_LIBRARIES SQLITE3_INCLUDE_DIR)

IF (SQLITE3_FOUND)
   INCLUDE (CheckLibraryExists)
   CHECK_LIBRARY_EXISTS (${SQLITE3_LIBRARIES} sqlite3_free "" SQLITE3_NEED_PREFIX)
ENDIF (SQLITE3_FOUND)

MARK_AS_ADVANCED (SQLITE3_INCLUDE_DIR SQLITE3_LIBRARIES)
